### ISSUE TITLE
"Cannot use JVMCI compiler: No JVMCI compiler found" error with JDK17

### ISSUE THREAD

**Issue by xuwei-k** [dwijnand/sbt-extras#331]
🤔 

https://github.com/dwijnand/sbt-extras/blob/787e7a6c0523cbd995708aec2815a21917315079/sbt#L261

**Comment by xuwei-k** [comment]
https://openjdk.java.net/jeps/410 🤔

**Comment by dunjil** [comment]
How did you fix this issue?

**Comment by keivanK1** [comment]
Try to run `sbt clean dist`. 

If the problem, under Ubuntu with Java installed, exists, then do the following:

- Installl sbt from [here](https://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html)
- `sbt clean dist`

Also, make sure `JAVA_HOME` is set correctly.
