### ISSUE TITLE
repo.typesafe.com down: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by twinkelmann** [dwijnand/sbt-extras#359]
Hi,

We include this tool in our build configuration. Since today, the build fails with the following error:

```
Downloading sbt launcher for 0.13.18:
  From  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.18/sbt-launch.jar
    To  /root/.sbt/launchers/0.13.18/sbt-launch.jar

Error: Invalid or corrupt jarfile /root/.sbt/launchers/0.13.18/sbt-launch.jar
```

Upon inspection, this error comes from your script. And it appears to be because the repo URL (https://repo.typesafe.com) is no longer valid. Seeing as it is hard coded in your tool, I wonder if there is any hope to find an alternative.

We are in the process of migrating our Scala backend to Java, but it's not done yet, and we still need the Scala build in the meantime. Right now, we cannot even work on the project, but thankfully the deployed version still works

**Comment by twinkelmann** [comment]
Testing again today, the repository `https://repo.typesafe.com/typesafe/ivy-releases/` now redirects to `https://scala.jfrog.io/ui/native/ivy-releases/` therefore working again as expected.

Let's hope it keeps working until we remove Scala from our project...

**Comment by SethTisue** [comment]
see sbt/sbt#7202 for details on what happened
